// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using optricon_home.Data;

#nullable disable

namespace optricon_home.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230331111333_RemovedContentAddedMediaObjects")]
    partial class RemovedContentAddedMediaObjects
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("optricon_home.Models.MediaObjects", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ButtonText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageAlt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MediaObjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ButtonText = "New Products",
                            ImageAlt = "Bird catching fish from River",
                            ImagePath = "/images/Birds.png",
                            Text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc ut aliquam aliquam, nunc nisl aliquet nisl, eget aliquam nisl nisl sit amet lorem.",
                            Title = "New Products"
                        },
                        new
                        {
                            Id = 2,
                            ButtonText = "View Events",
                            ImageAlt = "Group of Photographers with Long-lens",
                            ImagePath = "/images/Photographers.png",
                            Text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc ut aliquam aliquam, nunc nisl aliquet nisl, eget aliquam nisl nisl sit amet lorem.",
                            Title = "Field Events"
                        },
                        new
                        {
                            Id = 3,
                            ButtonText = "Read Article",
                            ImageAlt = "Landscape with Mountains",
                            ImagePath = "/images/Landscape.png",
                            Text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc ut aliquam aliquam, nunc nisl aliquet nisl, eget aliquam nisl nisl sit amet lorem.",
                            Title = "Latest News"
                        },
                        new
                        {
                            Id = 4,
                            ButtonText = "View Gallery",
                            ImageAlt = "Bird in tree",
                            ImagePath = "/images/Bird.png",
                            Text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc ut aliquam aliquam, nunc nisl aliquet nisl, eget aliquam nisl nisl sit amet lorem.",
                            Title = "Gallery"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
